# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: football_stats_development
  encoding: unicode
  user:  action
  host: localhost
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: football_stats_test
  encoding: unicode
  user: action
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: football_stats_production
  encoding: unicode
  pool: 5
  timeout: 5000
  